[font]
size = 10

[font.bold]
family = "MesloLGS NF"

[font.bold_italic]
family = "MesloLGS NF"

[font.italic]
family = "MesloLGS NF"

[font.normal]
family = "MesloLGS NF"

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 0.95
